using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace InventoryControl
{
    public partial class frmInvCatalog : Form
    {
        public frmInvCatalog()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            iC_exposureTableAdapter2.Fill(nmsDataSet2.IC_exposure);
        }

        private void frmInvCatalog_Load(object sender, EventArgs e)
        {
        }

        private void gridView1_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            gridView1.UpdateCurrentRow();
            iC_exposureTableAdapter2.Update(nmsDataSet2);
        }
    }
}
