using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using General;

namespace InventoryControl
{
    public partial class frmInvCatalog : DevExpress.XtraEditors.XtraForm
    {
        public frmInvCatalog()
        {
            Global.connectToDB();
            InventoryControl.Properties.Settings.Default["NMSConnectionString"] = Global.SQLCON;
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            iC_exposureTableAdapter2.Fill(dsExposure.IC_exposure);
            iC_zoneTableAdapter1.Fill(dsZone.IC_zone);
            iC_soilTableAdapter1.Fill(dsSoil.IC_soil);
            syS_SiteTableAdapter1.Fill(dsSite.SYS_Site);
            iC_inventoryGradesTableAdapter1.Fill(dsGrade.IC_inventoryGrades);
            iC_divisionTableAdapter1.Fill(dsDivision.IC_division);
            iC_enviromentTableAdapter1.Fill(dsEnviroment.IC_enviroment);
            iC_enviromentTableAdapter2.Fill(dsEnviroment.IC_enviroment);
            iC_typeTableAdapter1.Fill(dsType.IC_type);
        }

        private void frmInvCatalog_Load(object sender, EventArgs e)
        {
        }

        private void gridView1_CellValueChanged(object sender, DevExpress.XtraGrid.Views.Base.CellValueChangedEventArgs e)
        {
            gridView1.UpdateCurrentRow();
            iC_exposureTableAdapter2.Update(dsExposure);
        }
    }
}
